##############################################################
#
#                      TaberEssentials
#            "The official rewrite of Essentials"
#
#            (c) Samuel Taber and Joshua Hanson
#                 2019. All Rights Reserved
#
##############################################################
# These are all defaults. Feel free to change them as you please.
#
# This parameter allows the feature to disable fly on join.
# Many servers have this on for whatever reason, typically if
# a player was given temporary fly privileges.
disableFlyOnJoin: true
#
# The mail system has had a revamp. This parameter (when true)
# sends each player a notification if they have a new mail message
# in their inbox. (/notifications)
notifyMailOnJoin: true