name: TaberEssentials
author: Sam Taber
main: com.thetabergroup.tessentials.taberessentials
version: 1.1
description: complete rewrite and optimization of essentials.
commands:
    notifications:
        description: notification manager (beta)
    gamemode:
        description: gamemode manager (beta)